from pathlib import Path

CURRENT_PATH = Path().absolute()
CACHE_PATH = CURRENT_PATH / '.cache'
CACHE_UPLOAD_PATH = CACHE_PATH / 'upload_data'
CACHE_UPLOAD_DATA_PATH = CACHE_UPLOAD_PATH / 'data'
CACHE_UPLOAD_TEMPLATE_PATH = CACHE_UPLOAD_PATH / 'template'
CACHE_REFORMAT_PATH = CACHE_PATH / 'reformat_data'
CACHE_REFORMAT_DATA_PATH = CACHE_REFORMAT_PATH / 'data'
CACHE_REFORMAT_TEMPLATE_PATH = CACHE_REFORMAT_PATH / 'template'
